name: Yaml Lint
on: [push, pull_request] # yamllint disable-line rule:truthy
jobs:
  lintAllTheThings:
    name: Linting yml files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
